### ISSUE TITLE
Paper Review

### ISSUE THREAD

**Issue by n8stringham** [n8stringham/gensim-evaluations#6]
Hey Mike, I've got my paper uploaded in the repo under `paper/latex/emnlp`.

Thanks for taking the time to read it and looking forward to polishing it up next week. Have a good weekend!

**Comment by mikeizbicki** [comment]
I've had a first pass through it, and uploaded the changes to github.  There's still a lot more changes I want to do to it though, so I'm going to continue working on it Monday and upload another version tomorrow night.  Don't bother making any changes to the text right now since those will get deleted when I upload tomorrow.

In the meantime, there's some work for you to do on all the figures:

1. Perfecting the figures should be your priority right now.  If need be, I can write the text, but I won't be able to modify the figures.

1. Right now we're being inconsistent about how we're scoring topk and OddOneOut.  Sometimes it's a fraction out of 1 and sometimes it's the absolute number.  I don't particularly care which you choose to use, but it needs to be the same everywhere.  Some figures are better each way, so use your judgement.

1.  I've resized Figures 2,3, and 4.  Those are the final sizes that the figure should be in the paper, so you should adjust the sizes so that the format is correct.

1. Figure 2: the category names are fairly confusing as they are.  Can these be reformatted somehow?  For example, removing all the `gramX` labels and just grouping the grammatical vs non-grammatical categories?  This is likely going to be a confusing plot for reviewers no matter what, but we want to reduce that confusion as much as possible.

1. Figure 3: remove the dots, remove Sentiment task (RF) and remove Area Under Curve.  Can we change the label for Eisner Accuracy to be exactly what they use in their paper?  If not, just call it Eisner, et.al.  The key needs to be redone so there is no overlap with the lines.

1. Figure 4: This is the plot that needs the most work.  I think swapping the axes (so that the languages go down the y-axis in the same order as the table) and then having 3 columns, one for each category is the way to go.  We can talk about this more on zoom.  I suspect we can get this figure to fit on only half a page instead of a full page with some fiddling.

   We need to look into the Facets of Buddism category to see specifically what words Latin and Hebrew are doing well at.  

1. Table 1: I've changed the font size to `\tiny` and eliminated your resize box.  This is the absolute smallest that a font can be (and really it's already too small).  You need to fix the table so that it can fit in the margins at this size.  Some ideas are: eliminate the test set column, rotate language family 90 degrees or include it as a header row above each section, move unique tokens and min count onto two lines, abbreviate the languages (e.g. mid. eng. instead of middle english).

 We're doing pretty good length-wise right now, so it would also be goof to create a one column figure showing what the contents of the Biblical Figures, Facets of Buddhism and Facets of Hinduism categories contain.

**Comment by mikeizbicki** [comment]
I've uploaded my latest edits.  This version should be essentially content-complete, and just need edits on formatting and wording.

I've got a lot of FIXME annotations that you should look at and see how many of those you can fix.  The Intro and conclusion still need a bit of rewording, but I can be responsible for that if you'd like.  We should try to have a fully presentable draft ready on Thursday.

Are you free tomorrow at 2pm for zoom?  I think it would help for us to check in and make sure we're on the same page about everything.

**Comment by n8stringham** [comment]
Thanks Mike, I'll see you on zoom at 2pm to catch up.

**Comment by n8stringham** [comment]
Hey mike, I pushed what I have so far. Spent most of the day continuing to polish the figures. I also fixed a couple of the `fixmes` but I think there are still some more that I can tackle.

I have all the entries for the table showing what's in the test sets for the ds task in each language, but I was having trouble getting it to compile bc of the unicode.
